---
platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

inputs:
  - name: pcf-pipelines-maestro

run:
  path: pcf-pipelines-maestro/tasks/utils/teams-demolition/task.sh
